---
# THIS FILE IS USED AS AN EXAMPLE
# TO BE USED, IT MUST BE RENAMED `tracklet.yaml`
tracklet:
  maxHistory: 365 # Default: 365
  timeout: 30     # Default: 30
  retryDelay: 5   # Default: 5
  maxRetries: 10  # Default: 10
exchanges:
  binance:
    apiBaseUrl: https://api.binance.com
    apiKey: titi
    secretKey: toto
    includePairs: [] # Needed to avoid making 2k+ useless requests due to the fact Binance API is dumb
  coinbase:
    apiKey: titi
    secretKey: toto

